[global]
author=["Solal Jacob"]
webpage="https://ko-fi.com/solalretrogaming"
twitter="@s_on_vg"

[parse]
sourcefile=["toki.cpp"]
skip.Setnames=["tokip"]
skip.bootlegs=true

[buttons]
names = [
    { names="Shoot,Jump" }
]

[dipsw]
# too long for MiST OSD:
delete=[
    { Names=["coinage"] }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true, width=16, reverse=true },
    { name="gfx1", no_offset=true },
    { name="gfx2", no_offset=true  },
    { name="gfx3", no_offset=true  },
    { name="gfx4", no_offset=true  },
    { name="audiocpu", no_offset=true },
    { name="oki", no_offset=true },
    { name="proms", no_offset=true },
]

order=[ "maincpu", "gfx1", "gfx2", "gfx3", "gfx4", "audiocpu", "oki", "proms" ]
